// Generated file, do not modify manually!

// This file was automatically generated by lister-gen

package v1

// MWInjectorListerExpansion allows custom methods to be added to
// MWInjectorLister.
type MWInjectorListerExpansion interface{}

// MWInjectorNamespaceListerExpansion allows custom methods to be added to
// MWInjectorNamespaceLister.
type MWInjectorNamespaceListerExpansion interface{}
