// Generated file, do not modify manually!

// This file was automatically generated by informer-gen

package v1

import (
	internalinterfaces "github.com/dbenque/mw-injector/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// MWInjectors returns a MWInjectorInformer.
	MWInjectors() MWInjectorInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// MWInjectors returns a MWInjectorInformer.
func (v *version) MWInjectors() MWInjectorInformer {
	return &mWInjectorInformer{factory: v.SharedInformerFactory}
}
